meta_product_name: "Rhythm'n'Recipes"
meta_title: "Rhythm'n'Recipes - the secret ingredient to making cooking more fun"
meta_description: "Tailored recipes and soundtracks — just tell us what you're craving."
meta_image: "cover.png" # should exist in `app/assets/images/`
